# Generated by Django 5.0.7 on 2024-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tin_number',
        ),
    ]
