# Generated by Django 5.0.7 on 2024-07-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expenses', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
