# Generated by Django 5.0.7 on 2024-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin_number', models.IntegerField(blank=True, null=True)),
                ('stock_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='tin_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
