# Generated by Django 5.0.7 on 2024-07-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0002_profile_client_tin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tin_number',
        ),
    ]
