# Generated by Django 5.0.7 on 2024-07-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0002_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tin_number',
            field=models.CharField(max_length=15),
        ),
    ]
