# Generated by Django 5.0.7 on 2024-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxation', '0003_remove_client_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tin_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
